name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - Bug
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please complete the fields below in order.

  # 1) Assignee name (preferred)
  - type: dropdown
    id: assignee
    attributes:
      label: Preferred assignee
      description: This will not auto-assign. Triage will assign accordingly.
      options:
        - Unassigned
        - prodip-selise
        - hafizsamrat
        # Add your team's GitHub handles below
        # - alice
        # - bob
        # - charlie
      default: 0
    validations:
      required: true

  # 2) Priority with color-like emojis
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Choose the urgency of the fix.
      options:
        - 🟢 LOW
        - 🟠 MEDIUM
        - 🔴 HIGH
      default: 0
    validations:
      required: true

  # 3) Environment (dev, stage, production) with color-like emojis
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you observe the issue?
      options:
        - ⚪ DEV
        - 🟡 STAGE
        - 🔴 PRODUCTION
    validations:
      required: true

  # 4) Module selection with optional submodules, default "None"
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the affected module/submodule.
      options:
        - Unassigned
        # Example structure: "Module > Submodule"
        - Day Planning > Shifts
        - Day Planning > Absences
        - Day Planning > Checklists
        - Monitor
        - Guide
        - To-Do
        - Training
        - Configurator
        # Add all project modules and submodules above
      default: 0
    validations:
      required: true

  # 5) Bug description (details of the bug)
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Provide a clear and concise description of the bug.
      placeholder: What happened? Include error messages and context.
    validations:
      required: true

  # 6) Expected behavior
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: The expected behavior is...
    validations:
      required: true

  # 7) Recreation steps (if needed)
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce (if needed)
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Observe ...
    validations:
      required: false

  # 8) Reporter name
  - type: input
    id: reporter
    attributes:
      label: Reporter name
      description: Your name or GitHub username.
      placeholder: e.g., @your-handle
    validations:
      required: false

  # 9) Additional media attach options (links + guidance)
  - type: markdown
    attributes:
      value: |
        ### Attachments
        You can drag-and-drop screenshots, videos, and log files into the issue body **after submission**.
        If the files are hosted elsewhere, paste their links below.
  - type: textarea
    id: attachments-links
    attributes:
      label: Links to media/logs (optional)
      description: Paste URLs to screenshots, videos, or logs.
      placeholder: https://example.com/screenshot.png
    validations:
      required: false

  # 10) Additional supporting info (if needed)
  - type: textarea
    id: additional-info
    attributes:
      label: Additional supporting info (optional)
      description: Any other relevant details (build numbers, commit hashes, feature flags, etc.).
      placeholder: Add any extra context here.
    validations:
      required: false
