name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - bug
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please provide the details below. Fields marked with (*) are required.
        ---

  # Preferred assignee (cannot auto-assign, but helps triage)
  - type: dropdown
    id: assignee
    attributes:
      label: Assignee
      multiple: true
      options:
        - Prodip Datta
        - Hafizur Rahman
        - Dhiman Sarkar
        - Rashedul Islam
        - Thouhidur Forkan
        - Saiful Alam
        - Golam Rabbani
        - Amar Tanvee
        - Sazia Afroz
        - Sanjana Chowdhury
        - Md Imon
        - Nazmul Islam Hridoy
    validations:
      required: true

  # Priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority (*)
      options:
        - 🟢 LOW
        - 🟠 MEDIUM
        - 🔴 HIGH
      default: 0
    validations:
      required: true

  # Environment
  - type: checkboxes
    id: environment
    attributes:
      label: Environment (*)
      options:
        - label: ⚪ DEV
        - label: 🟡 STAGE
        - label: 🔴 PRODUCTION
    validations:
      required: true

  # Module/Submodule
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the affected module/submodule.
      multiple: true
      options:
        - Day Planning
          - Shifts
          - Absences
          - Checklists
        - Monitor
        - Guide
        - To-Do
        - Training
        - Configurator
        - Workflow-Navi
    validations:
      required: true

  # Bug description
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description (*)
      placeholder: What happened? Include error messages and context.
    validations:
      required: true

  # Expected behavior
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior (*)
      placeholder: Describe what you expected to happen
    validations:
      required: true

  # Repro steps
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce (if needed)
      description: Keep it short; use a numbered list.
      value: |
        1. Go to …
        2. Click …
        3. Observe …
    validations:
      required: false

  # Reporter
  - type: input
    id: reporter
    attributes:
      label: Reporter
      placeholder: e.g., @john-doe
    validations:
      required: false

  # Attachments guidance + links
  - type: markdown
    attributes:
      value: |
        **Attachments**
        - Drag & drop screenshots, videos, and logs **after submitting**.
        - Or paste links below.

  - type: textarea
    id: attachments-links
    attributes:
      label: Links to media/logs (optional)
      placeholder: https://… (Drive, OneDrive, S3, etc.)

  # Additional info
  - type: textarea
    id: additional-info
    attributes:
      label: Additional supporting info (optional)
      placeholder: console log, cUrl, payload, api endpoint, etc.

  # Optional sanity checks
  - type: checkboxes
    id: checklist
    attributes:
      label: Quick checks (optional)
      options:
        - label: I cleared cache and tried again
